### ISSUE TITLE
Create README.md

### ISSUE THREAD

**Issue by katieb1** [UBC-MDS/pymagine#5]
Includes:

- [x] High level summary

- [x] Bulleted list of function + short description

- [x] Paragraph describing where package fits into python environment

- [x]  Edits from collaborators

**Comment by brendoncampbell** [comment]
@katieb1 @Sukriti1312 @trevorkwan feel free to update your function description and add/update any other details in the README as you see fit

**Comment by trevorkwan** [comment]
@brendoncampbell looks good!
